name       : perl-canary-stability
version    : '2012'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Canary-Stability-2012.tar.gz : fd240b111d834dbae9630c59b42fae2145ca35addc1965ea311edf0d07817107
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Canary::Stability - canary to check perl compatibility for schmorp's
    modules
description: |
    This module is used by Schmorp's modules during configuration stage to test the installed perl for compatibility with his modules.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
